print ("Hi")
print ("I am Zack")
print ("I live in Australia")
print ("I like to read and fish")
print ("I can speak Chinese")
print ("In my spare time, I like to play games")
print ("I also like to listen to music")
print ("2+2", 2+2)
print (2+2)
